version: '3.8'
services:
    app:
          container_name: company_product
          restart: always
          build: .
          ports:
            - "${PORT}:${PORT}"
          links: 
            - mongo
    mongo:
       container_name: mongo
       image: mongo     